---
prometheus.enabled: true
prometheus.port: 8080
exampletemplateservice.port: 5000
exampletemplateservice.hostName: 0.0.0.0
exampletemplateservice.logFile: null
exampletemplateservice.logLevel: info
fastapi.logLevel: warning
